services:
  angular:
    build: ./frontend
    ports:
      - "4200:4200" # Map host port 80 to container port 80 (Nginx)
    depends_on:
      - express

  express:
    build: ./backend
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000 (Express)